export const sampleData = {
  blocks: [
    {
      id: "a",
      description:
        "Under ancient cypress trees, the air carries a faint scent of resin and earth. Time seems slower here, as sunlight filters through the dense canopy.",
      maxSlots: 20,
      slots: [
        {
          slot: "A1",
          name: "Carl Griffin",
          gender: "male",
          age: 34,
          email: "carl.griffin@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/44.jpg",
        },
        {
          slot: "A2",
          name: "Alfred Harvey",
          gender: "male",
          age: 28,
          email: "alfred.harvey@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/10.jpg",
        },
        {
          slot: "A3",
          name: "Sofia Obrien",
          gender: "female",
          age: 59,
          email: "sofia.obrien@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/66.jpg",
        },
        {
          slot: "A4",
          name: "Willie Adams",
          gender: "female",
          age: 27,
          email: "willie.adams@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/78.jpg",
        },
        {
          slot: "A5",
          name: "Dana Soto",
          gender: "female",
          age: 44,
          email: "dana.soto@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/55.jpg",
        },
        {
          slot: "A6",
          name: "Zachary Li",
          gender: "male",
          age: 44,
          email: "zachary.li@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/54.jpg",
        },
        {
          slot: "A7",
          name: "Maya Jones",
          gender: "female",
          age: 74,
          email: "maya.jones@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/44.jpg",
        },
        {
          slot: "A8",
          name: "David Jean-Baptiste",
          gender: "male",
          age: 60,
          email: "david.jean-baptiste@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/28.jpg",
        },
      ].map((person) => ({
        ...person,
        deathDate: randomDate(),
      })),
    },
    {
      id: "b",
      description:
        "A serene area near the marble walkway, where footsteps echo softly between columns. The stone surface remains cool even under the afternoon sun.",
      maxSlots: 20,
      slots: [
        {
          slot: "B1",
          name: "Oliver Pelletier",
          gender: "male",
          age: 68,
          email: "oliver.pelletier@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/64.jpg",
        },
        {
          slot: "B2",
          name: "Dale Simpson",
          gender: "male",
          age: 69,
          email: "dale.simpson@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/57.jpg",
        },
        {
          slot: "B3",
          name: "Liam Ennis",
          gender: "male",
          age: 43,
          email: "liam.ennis@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/85.jpg",
        },
        {
          slot: "B4",
          name: "Elizabeth Ginnish",
          gender: "female",
          age: 53,
          email: "elizabeth.ginnish@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/66.jpg",
        },
        {
          slot: "B5",
          name: "Jeffrey Mcdonalid",
          gender: "male",
          age: 62,
          email: "jeffrey.mcdonalid@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/86.jpg",
        },
        {
          slot: "B6",
          name: "Sergio Thompson",
          gender: "male",
          age: 73,
          email: "sergio.thompson@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/56.jpg",
        },
        {
          slot: "B7",
          name: "Beth Martinez",
          gender: "female",
          age: 55,
          email: "beth.martinez@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/41.jpg",
        },
        {
          slot: "B8",
          name: "Curtis Mitchell",
          gender: "male",
          age: 80,
          email: "curtis.mitchell@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/34.jpg",
        },
        {
          slot: "B9",
          name: "Rose Smith",
          gender: "female",
          age: 53,
          email: "rose.smith@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/80.jpg",
        },
        {
          slot: "B10",
          name: "Bertha Chapman",
          gender: "female",
          age: 44,
          email: "bertha.chapman@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/89.jpg",
        },
        {
          slot: "B11",
          name: "Ethan Perez",
          gender: "male",
          age: 54,
          email: "ethan.perez@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/47.jpg",
        },
        {
          slot: "B12",
          name: "Ava Pelletier",
          gender: "female",
          age: 45,
          email: "ava.pelletier@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/51.jpg",
        },
        {
          slot: "B13",
          name: "Leah Romero",
          gender: "female",
          age: 32,
          email: "leah.romero@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/17.jpg",
        },
        {
          slot: "B14",
          name: "Amelia Clarke",
          gender: "female",
          age: 28,
          email: "amelia.clarke@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/51.jpg",
        },
      ].map((person) => ({
        ...person,
        deathDate: randomDate(),
      })),
    },
    {
      id: "c",
      description:
        "Nestled by the chapel ruins, moss covers fragments of old stone. The silence is broken only by distant bells carried on the wind.",
      maxSlots: 20,
      slots: [
        {
          slot: "C1",
          name: "Barb Hale",
          gender: "female",
          age: 76,
          email: "barb.hale@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/25.jpg",
        },
        {
          slot: "C2",
          name: "Adam Brown",
          gender: "male",
          age: 59,
          email: "adam.brown@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/28.jpg",
        },
        {
          slot: "C3",
          name: "Barb King",
          gender: "female",
          age: 67,
          email: "barb.king@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/2.jpg",
        },
        {
          slot: "C4",
          name: "Charles Lévesque",
          gender: "male",
          age: 26,
          email: "charles.levesque@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/0.jpg",
        },
        {
          slot: "C5",
          name: "Faith Brooks",
          gender: "female",
          age: 76,
          email: "faith.brooks@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/2.jpg",
        },
        {
          slot: "C6",
          name: "Nicole Murray",
          gender: "female",
          age: 68,
          email: "nicole.murray@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/13.jpg",
        },
        {
          slot: "C7",
          name: "Alex Porter",
          gender: "female",
          age: 63,
          email: "alex.porter@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/89.jpg",
        },
        {
          slot: "C8",
          name: "Benjamin Chu",
          gender: "male",
          age: 48,
          email: "benjamin.chu@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/52.jpg",
        },
        {
          slot: "C9",
          name: "Kyle Alexander",
          gender: "male",
          age: 63,
          email: "kyle.alexander@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/61.jpg",
        },
        {
          slot: "C10",
          name: "Benjamin Slawa",
          gender: "male",
          age: 42,
          email: "benjamin.slawa@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/1.jpg",
        },
        {
          slot: "C11",
          name: "Logan Knight",
          gender: "male",
          age: 31,
          email: "logan.knight@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/32.jpg",
        },
        {
          slot: "C12",
          name: "Travis Allen",
          gender: "male",
          age: 61,
          email: "travis.allen@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/59.jpg",
        },
        {
          slot: "C13",
          name: "Erika Silva",
          gender: "female",
          age: 52,
          email: "erika.silva@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/86.jpg",
        },
        {
          slot: "C14",
          name: "Charles Harris",
          gender: "male",
          age: 56,
          email: "charles.harris@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/16.jpg",
        },
        {
          slot: "C15",
          name: "Maxime Martin",
          gender: "male",
          age: 76,
          email: "maxime.martin@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/19.jpg",
        },
        {
          slot: "C16",
          name: "Ava Walker",
          gender: "female",
          age: 80,
          email: "ava.walker@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/14.jpg",
        },
        {
          slot: "C17",
          name: "Cindy Sutton",
          gender: "female",
          age: 69,
          email: "cindy.sutton@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/66.jpg",
        },
        {
          slot: "C18",
          name: "Melanie Schmidt",
          gender: "female",
          age: 27,
          email: "melanie.schmidt@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/70.jpg",
        },
        {
          slot: "C19",
          name: "John Shaw",
          gender: "male",
          age: 25,
          email: "john.shaw@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/53.jpg",
        },
        {
          slot: "C20",
          name: "Avery Adams",
          gender: "female",
          age: 38,
          email: "avery.adams@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/52.jpg",
        },
      ].map((person) => ({
        ...person,
        deathDate: randomDate(),
      })),
    },
    {
      id: "d",
      description:
        "Beside the northern slope, tall grasses sway gently in the breeze. The scent of pine lingers, reminding travelers of the highlands beyond.",
      maxSlots: 20,
      slots: [
        {
          slot: "D1",
          name: "Abbie Young",
          gender: "female",
          age: 25,
          email: "abbie.young@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/93.jpg",
        },
        {
          slot: "D2",
          name: "Jennifer Richards",
          gender: "female",
          age: 67,
          email: "jennifer.richards@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/32.jpg",
        },
        {
          slot: "D3",
          name: "Alexis Lavoie",
          gender: "female",
          age: 48,
          email: "alexis.lavoie@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/49.jpg",
        },
        {
          slot: "D4",
          name: "Emma Smith",
          gender: "female",
          age: 38,
          email: "emma.smith@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/86.jpg",
        },
        {
          slot: "D5",
          name: "Sophie Addy",
          gender: "female",
          age: 26,
          email: "sophie.addy@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/80.jpg",
        },
        {
          slot: "D6",
          name: "Glen Black",
          gender: "male",
          age: 38,
          email: "glen.black@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/95.jpg",
        },
        {
          slot: "D7",
          name: "Aubrey Grewal",
          gender: "female",
          age: 42,
          email: "aubrey.grewal@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/86.jpg",
        },
        {
          slot: "D8",
          name: "Leo Mitchell",
          gender: "male",
          age: 31,
          email: "leo.mitchell@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/58.jpg",
        },
        {
          slot: "D9",
          name: "Rick Richardson",
          gender: "male",
          age: 70,
          email: "rick.richardson@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/42.jpg",
        },
        {
          slot: "D10",
          name: "Susan Snyder",
          gender: "female",
          age: 66,
          email: "susan.snyder@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/24.jpg",
        },
      ].map((person) => ({
        ...person,
        deathDate: randomDate(),
      })),
    },
    {
      id: "e",
      description:
        "A sunlit corner surrounded by ivy walls, where the warmth feels almost sacred. Small wildflowers bloom through cracks in the ancient stone.",
      maxSlots: 20,
      slots: [
        {
          slot: "E1",
          name: "Louis Dunn",
          gender: "male",
          age: 45,
          email: "louis.dunn@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/78.jpg",
        },
        {
          slot: "E2",
          name: "Caroline Castillo",
          gender: "female",
          age: 60,
          email: "caroline.castillo@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/93.jpg",
        },
        {
          slot: "E3",
          name: "Alexander Miller",
          gender: "male",
          age: 43,
          email: "alexander.miller@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/78.jpg",
        },
        {
          slot: "E4",
          name: "Gabrielle Walker",
          gender: "female",
          age: 76,
          email: "gabrielle.walker@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/10.jpg",
        },
        {
          slot: "E5",
          name: "Sophia Pelletier",
          gender: "female",
          age: 71,
          email: "sophia.pelletier@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/20.jpg",
        },
        {
          slot: "E6",
          name: "Juliette Macdonald",
          gender: "female",
          age: 48,
          email: "juliette.macdonald@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/54.jpg",
        },
        {
          slot: "E7",
          name: "Ashley Rice",
          gender: "female",
          age: 69,
          email: "ashley.rice@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/10.jpg",
        },
        {
          slot: "E8",
          name: "Eleanor Gomez",
          gender: "female",
          age: 59,
          email: "eleanor.gomez@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/16.jpg",
        },
        {
          slot: "E9",
          name: "Tiffany Carroll",
          gender: "female",
          age: 63,
          email: "tiffany.carroll@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/89.jpg",
        },
        {
          slot: "E10",
          name: "Daniel Miller",
          gender: "male",
          age: 73,
          email: "daniel.miller@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/63.jpg",
        },
        {
          slot: "E11",
          name: "Regina Byrd",
          gender: "female",
          age: 50,
          email: "regina.byrd@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/78.jpg",
        },
        {
          slot: "E12",
          name: "Christina Riley",
          gender: "female",
          age: 68,
          email: "christina.riley@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/73.jpg",
        },
        {
          slot: "E13",
          name: "Chris Ortiz",
          gender: "male",
          age: 73,
          email: "chris.ortiz@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/50.jpg",
        },
        {
          slot: "E14",
          name: "Angela Smith",
          gender: "female",
          age: 29,
          email: "angela.smith@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/24.jpg",
        },
        {
          slot: "E15",
          name: "Barbara Horton",
          gender: "female",
          age: 47,
          email: "barbara.horton@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/32.jpg",
        },
        {
          slot: "E16",
          name: "Debra Fernandez",
          gender: "female",
          age: 46,
          email: "debra.fernandez@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/15.jpg",
        },
      ].map((person) => ({
        ...person,
        deathDate: randomDate(),
      })),
    },
    {
      id: "f",
      description:
        "Overlooking a small pond, the water’s surface mirrors drifting clouds. The gentle hum of insects fills the still air around it.",
      maxSlots: 20,
      slots: [
        {
          slot: "F1",
          name: "Marilou Mitchell",
          gender: "female",
          age: 75,
          email: "marilou.mitchell@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/43.jpg",
        },
        {
          slot: "F2",
          name: "Barb Lawson",
          gender: "female",
          age: 25,
          email: "barb.lawson@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/26.jpg",
        },
        {
          slot: "F3",
          name: "Todd Rogers",
          gender: "male",
          age: 51,
          email: "todd.rogers@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/60.jpg",
        },
        {
          slot: "F4",
          name: "Sylvia Soto",
          gender: "female",
          age: 62,
          email: "sylvia.soto@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/6.jpg",
        },
        {
          slot: "F5",
          name: "Sergio Steward",
          gender: "male",
          age: 61,
          email: "sergio.steward@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/94.jpg",
        },
        {
          slot: "F6",
          name: "Benjamin Brar",
          gender: "male",
          age: 31,
          email: "benjamin.brar@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/94.jpg",
        },
        {
          slot: "F7",
          name: "Gabriel Patel",
          gender: "male",
          age: 29,
          email: "gabriel.patel@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/34.jpg",
        },
        {
          slot: "F8",
          name: "Camille Roy",
          gender: "female",
          age: 72,
          email: "camille.roy@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/21.jpg",
        },
        {
          slot: "F9",
          name: "Clayton Vargas",
          gender: "male",
          age: 47,
          email: "clayton.vargas@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/18.jpg",
        },
        {
          slot: "F10",
          name: "Charlie Mackay",
          gender: "female",
          age: 32,
          email: "charlie.mackay@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/31.jpg",
        },
        {
          slot: "F11",
          name: "Felecia Medina",
          gender: "female",
          age: 27,
          email: "felecia.medina@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/81.jpg",
        },
        {
          slot: "F12",
          name: "Same Willis",
          gender: "male",
          age: 76,
          email: "same.willis@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/93.jpg",
        },
      ].map((person) => ({
        ...person,
        deathDate: randomDate(),
      })),
    },
    {
      id: "g",
      description:
        "This secluded area rests under oak shadows, where light and dark intertwine. Fallen leaves create a soft path that muffles every step.",
      maxSlots: 20,
      slots: [
        {
          slot: "G1",
          name: "Mattie Chambers",
          gender: "female",
          age: 51,
          email: "mattie.chambers@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/48.jpg",
        },
        {
          slot: "G2",
          name: "Kaitlin Stevens",
          gender: "female",
          age: 40,
          email: "kaitlin.stevens@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/45.jpg",
        },
        {
          slot: "G3",
          name: "Hailey Novak",
          gender: "female",
          age: 68,
          email: "hailey.novak@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/19.jpg",
        },
        {
          slot: "G4",
          name: "Sarah Wilson",
          gender: "female",
          age: 60,
          email: "sarah.wilson@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/91.jpg",
        },
        {
          slot: "G5",
          name: "Eliza Murphy",
          gender: "female",
          age: 43,
          email: "eliza.murphy@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/51.jpg",
        },
        {
          slot: "G6",
          name: "Bobby Price",
          gender: "male",
          age: 58,
          email: "bobby.price@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/46.jpg",
        },
        {
          slot: "G7",
          name: "Zoe Anderson",
          gender: "female",
          age: 71,
          email: "zoe.anderson@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/53.jpg",
        },
        {
          slot: "G8",
          name: "Carter Roy",
          gender: "male",
          age: 64,
          email: "carter.roy@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/48.jpg",
        },
        {
          slot: "G9",
          name: "Danielle Brown",
          gender: "female",
          age: 32,
          email: "danielle.brown@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/52.jpg",
        },
        {
          slot: "G10",
          name: "Dustin Banks",
          gender: "male",
          age: 75,
          email: "dustin.banks@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/7.jpg",
        },
        {
          slot: "G11",
          name: "Louis Jones",
          gender: "male",
          age: 74,
          email: "louis.jones@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/67.jpg",
        },
        {
          slot: "G12",
          name: "Addison Gagnon",
          gender: "female",
          age: 63,
          email: "addison.gagnon@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/39.jpg",
        },
        {
          slot: "G13",
          name: "Logan Chow",
          gender: "male",
          age: 67,
          email: "logan.chow@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/42.jpg",
        },
        {
          slot: "G14",
          name: "Maya Li",
          gender: "female",
          age: 63,
          email: "maya.li@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/23.jpg",
        },
        {
          slot: "G15",
          name: "Florence Williamson",
          gender: "female",
          age: 59,
          email: "florence.williamson@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/91.jpg",
        },
        {
          slot: "G16",
          name: "Jose Jacobs",
          gender: "male",
          age: 78,
          email: "jose.jacobs@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/43.jpg",
        },
        {
          slot: "G17",
          name: "Lauren Austin",
          gender: "female",
          age: 58,
          email: "lauren.austin@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/83.jpg",
        },
        {
          slot: "G18",
          name: "Nathan Liu",
          gender: "male",
          age: 78,
          email: "nathan.liu@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/45.jpg",
        },
      ].map((person) => ({
        ...person,
        deathDate: randomDate(),
      })),
    },
    {
      id: "h",
      description:
        "Gravel paths wind through this section, bordered by low stone markers. Each corner reveals a hidden alcove cloaked in quiet stillness.",
      maxSlots: 20,
      slots: [
        {
          slot: "H1",
          name: "Charles Ma",
          gender: "male",
          age: 71,
          email: "charles.ma@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/4.jpg",
        },
        {
          slot: "H2",
          name: "Oliver Ouellet",
          gender: "male",
          age: 76,
          email: "oliver.ouellet@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/57.jpg",
        },
        {
          slot: "H3",
          name: "Sebastian Jenkins",
          gender: "male",
          age: 58,
          email: "sebastian.jenkins@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/89.jpg",
        },
        {
          slot: "H4",
          name: "Nevaeh Owens",
          gender: "female",
          age: 76,
          email: "nevaeh.owens@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/24.jpg",
        },
        {
          slot: "H5",
          name: "Herman Pierce",
          gender: "male",
          age: 42,
          email: "herman.pierce@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/87.jpg",
        },
        {
          slot: "H6",
          name: "Sean Ferguson",
          gender: "male",
          age: 33,
          email: "sean.ferguson@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/84.jpg",
        },
        {
          slot: "H7",
          name: "Charlotte Jean-Baptiste",
          gender: "female",
          age: 55,
          email: "charlotte.jean-baptiste@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/3.jpg",
        },
        {
          slot: "H8",
          name: "Jesse Reyes",
          gender: "male",
          age: 67,
          email: "jesse.reyes@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/37.jpg",
        },
        {
          slot: "H9",
          name: "Art Owens",
          gender: "male",
          age: 56,
          email: "art.owens@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/26.jpg",
        },
      ].map((person) => ({
        ...person,
        deathDate: randomDate(),
      })),
    },
    {
      id: "i",
      description:
        "Beyond the central archway, the space opens to a tranquil courtyard. The air feels heavier here, as if history itself lingers unseen.",
      maxSlots: 20,
      slots: [
        {
          slot: "I1",
          name: "Phil Porter",
          gender: "male",
          age: 73,
          email: "phil.porter@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/49.jpg",
        },
        {
          slot: "I2",
          name: "Carolyn Hicks",
          gender: "female",
          age: 61,
          email: "carolyn.hicks@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/76.jpg",
        },
        {
          slot: "I3",
          name: "Lewis Jenkins",
          gender: "male",
          age: 51,
          email: "lewis.jenkins@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/73.jpg",
        },
        {
          slot: "I4",
          name: "Francisco Marshall",
          gender: "male",
          age: 45,
          email: "francisco.marshall@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/22.jpg",
        },
        {
          slot: "I5",
          name: "Emilie Campbell",
          gender: "female",
          age: 71,
          email: "emilie.campbell@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/30.jpg",
        },
        {
          slot: "I6",
          name: "Alyssa Morales",
          gender: "female",
          age: 32,
          email: "alyssa.morales@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/3.jpg",
        },
        {
          slot: "I7",
          name: "Judy Miles",
          gender: "female",
          age: 49,
          email: "judy.miles@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/15.jpg",
        },
        {
          slot: "I8",
          name: "Janet Owens",
          gender: "female",
          age: 43,
          email: "janet.owens@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/87.jpg",
        },
        {
          slot: "I9",
          name: "Delphine Patel",
          gender: "female",
          age: 71,
          email: "delphine.patel@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/63.jpg",
        },
        {
          slot: "I10",
          name: "Landon Hughes",
          gender: "male",
          age: 78,
          email: "landon.hughes@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/67.jpg",
        },
        {
          slot: "I11",
          name: "Marvin Chavez",
          gender: "male",
          age: 27,
          email: "marvin.chavez@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/21.jpg",
        },
        {
          slot: "I12",
          name: "Darren Douglas",
          gender: "male",
          age: 46,
          email: "darren.douglas@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/80.jpg",
        },
        {
          slot: "I13",
          name: "Anthony Liu",
          gender: "male",
          age: 53,
          email: "anthony.liu@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/83.jpg",
        },
        {
          slot: "I14",
          name: "Victoria Smith",
          gender: "female",
          age: 57,
          email: "victoria.smith@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/37.jpg",
        },
        {
          slot: "I15",
          name: "Arthur Wilson",
          gender: "male",
          age: 43,
          email: "arthur.wilson@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/91.jpg",
        },
        {
          slot: "I16",
          name: "Louis Bélanger",
          gender: "male",
          age: 69,
          email: "louis.belanger@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/60.jpg",
        },
        {
          slot: "I17",
          name: "Harold Obrien",
          gender: "male",
          age: 52,
          email: "harold.obrien@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/64.jpg",
        },
        {
          slot: "I18",
          name: "Amy Castro",
          gender: "female",
          age: 79,
          email: "amy.castro@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/15.jpg",
        },
        {
          slot: "I19",
          name: "Scarlett Reyes",
          gender: "female",
          age: 62,
          email: "scarlett.reyes@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/59.jpg",
        },
        {
          slot: "I20",
          name: "Melvin Rice",
          gender: "male",
          age: 44,
          email: "melvin.rice@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/21.jpg",
        },
      ].map((person) => ({
        ...person,
        deathDate: randomDate(),
      })),
    },
    {
      id: "j",
      description:
        "Quietly tucked near the south gate, the area is rarely disturbed. Morning mist often settles here, softening the outlines of the stones.",
      maxSlots: 20,
      slots: [
        {
          slot: "J1",
          name: "Marilou Lévesque",
          gender: "female",
          age: 48,
          email: "marilou.levesque@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/15.jpg",
        },
        {
          slot: "J2",
          name: "Mathew Brown",
          gender: "male",
          age: 67,
          email: "mathew.brown@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/56.jpg",
        },
        {
          slot: "J3",
          name: "Dylan Henderson",
          gender: "male",
          age: 59,
          email: "dylan.henderson@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/12.jpg",
        },
        {
          slot: "J4",
          name: "Mathis Harcourt",
          gender: "male",
          age: 33,
          email: "mathis.harcourt@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/35.jpg",
        },
        {
          slot: "J5",
          name: "Cory James",
          gender: "male",
          age: 46,
          email: "cory.james@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/25.jpg",
        },
        {
          slot: "J6",
          name: "Addison Neal",
          gender: "female",
          age: 75,
          email: "addison.neal@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/69.jpg",
        },
        {
          slot: "J7",
          name: "Zachary Pelletier",
          gender: "male",
          age: 70,
          email: "zachary.pelletier@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/80.jpg",
        },
      ].map((person) => ({
        ...person,
        deathDate: randomDate(),
      })),
    },
    {
      id: "k",
      description:
        "This block lies on elevated ground, granting a view of the valley below. Breezes pass through often, carrying whispers of the forest edge.",
      maxSlots: 20,
      slots: [
        {
          slot: "K1",
          name: "Olivier Gagné",
          gender: "male",
          age: 47,
          email: "olivier.gagne@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/61.jpg",
        },
        {
          slot: "K2",
          name: "Bob Roberts",
          gender: "male",
          age: 47,
          email: "bob.roberts@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/52.jpg",
        },
        {
          slot: "K3",
          name: "Diana Bennett",
          gender: "female",
          age: 52,
          email: "diana.bennett@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/78.jpg",
        },
        {
          slot: "K4",
          name: "Chad Richards",
          gender: "male",
          age: 54,
          email: "chad.richards@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/60.jpg",
        },
        {
          slot: "K5",
          name: "Peter Meyer",
          gender: "male",
          age: 57,
          email: "peter.meyer@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/5.jpg",
        },
        {
          slot: "K6",
          name: "Herbert Nelson",
          gender: "male",
          age: 71,
          email: "herbert.nelson@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/30.jpg",
        },
        {
          slot: "K7",
          name: "Tomothy Bennett",
          gender: "male",
          age: 73,
          email: "tomothy.bennett@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/3.jpg",
        },
        {
          slot: "K8",
          name: "Melissa Boyd",
          gender: "female",
          age: 60,
          email: "melissa.boyd@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/33.jpg",
        },
        {
          slot: "K9",
          name: "Tracey Woods",
          gender: "female",
          age: 25,
          email: "tracey.woods@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/3.jpg",
        },
        {
          slot: "K10",
          name: "Jesse Herrera",
          gender: "male",
          age: 63,
          email: "jesse.herrera@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/38.jpg",
        },
        {
          slot: "K11",
          name: "Chloe Grewal",
          gender: "female",
          age: 65,
          email: "chloe.grewal@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/90.jpg",
        },
      ].map((person) => ({
        ...person,
        deathDate: randomDate(),
      })),
    },
    {
      id: "l",
      description:
        "Near the fountain courtyard, the sound of water echoes between carved pillars. Pigeons gather here, unafraid of the gentle visitors passing by.",
      maxSlots: 20,
      slots: [
        {
          slot: "L1",
          name: "Ella Campbell",
          gender: "female",
          age: 41,
          email: "ella.campbell@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/11.jpg",
        },
        {
          slot: "L2",
          name: "Clarence Hawkins",
          gender: "male",
          age: 43,
          email: "clarence.hawkins@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/62.jpg",
        },
        {
          slot: "L3",
          name: "Hannah Williams",
          gender: "female",
          age: 62,
          email: "hannah.williams@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/17.jpg",
        },
        {
          slot: "L4",
          name: "Sophia Abraham",
          gender: "female",
          age: 60,
          email: "sophia.abraham@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/24.jpg",
        },
        {
          slot: "L5",
          name: "Sarah Jones",
          gender: "female",
          age: 29,
          email: "sarah.jones@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/19.jpg",
        },
        {
          slot: "L6",
          name: "Tony Davidson",
          gender: "male",
          age: 79,
          email: "tony.davidson@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/66.jpg",
        },
        {
          slot: "L7",
          name: "Amy Miller",
          gender: "female",
          age: 63,
          email: "amy.miller@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/46.jpg",
        },
        {
          slot: "L8",
          name: "Rebecca Mason",
          gender: "female",
          age: 73,
          email: "rebecca.mason@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/43.jpg",
        },
        {
          slot: "L9",
          name: "Seth Payne",
          gender: "male",
          age: 41,
          email: "seth.payne@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/80.jpg",
        },
        {
          slot: "L10",
          name: "Clayton Moore",
          gender: "male",
          age: 30,
          email: "clayton.moore@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/64.jpg",
        },
        {
          slot: "L11",
          name: "Elizabeth Gill",
          gender: "female",
          age: 54,
          email: "elizabeth.gill@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/56.jpg",
        },
        {
          slot: "L12",
          name: "Melodie Miller",
          gender: "female",
          age: 30,
          email: "melodie.miller@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/79.jpg",
        },
        {
          slot: "L13",
          name: "Rosie Olson",
          gender: "female",
          age: 44,
          email: "rosie.olson@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/47.jpg",
        },
      ].map((person) => ({
        ...person,
        deathDate: randomDate(),
      })),
    },
    {
      id: "m",
      description:
        "Along the western edge, golden light lingers longer before dusk. The stones here are warm to the touch, keeping the day’s memory.",
      maxSlots: 20,
      slots: [
        {
          slot: "M1",
          name: "Aiden Roy",
          gender: "male",
          age: 71,
          email: "aiden.roy@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/52.jpg",
        },
        {
          slot: "M2",
          name: "Ariane Johnson",
          gender: "female",
          age: 37,
          email: "ariane.johnson@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/59.jpg",
        },
        {
          slot: "M3",
          name: "Marcia Matthews",
          gender: "female",
          age: 73,
          email: "marcia.matthews@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/48.jpg",
        },
        {
          slot: "M4",
          name: "Soham Watson",
          gender: "male",
          age: 69,
          email: "soham.watson@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/92.jpg",
        },
        {
          slot: "M5",
          name: "Logan Walker",
          gender: "male",
          age: 74,
          email: "logan.walker@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/48.jpg",
        },
        {
          slot: "M6",
          name: "Renee Olson",
          gender: "female",
          age: 77,
          email: "renee.olson@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/73.jpg",
        },
        {
          slot: "M7",
          name: "Ronald Rivera",
          gender: "male",
          age: 40,
          email: "ronald.rivera@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/42.jpg",
        },
        {
          slot: "M8",
          name: "Elaine Jackson",
          gender: "female",
          age: 29,
          email: "elaine.jackson@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/18.jpg",
        },
        {
          slot: "M9",
          name: "Mia Chu",
          gender: "female",
          age: 57,
          email: "mia.chu@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/96.jpg",
        },
        {
          slot: "M10",
          name: "Stanley Rivera",
          gender: "male",
          age: 48,
          email: "stanley.rivera@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/53.jpg",
        },
        {
          slot: "M11",
          name: "Carter Lo",
          gender: "male",
          age: 34,
          email: "carter.lo@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/16.jpg",
        },
        {
          slot: "M12",
          name: "Lucas Abraham",
          gender: "male",
          age: 58,
          email: "lucas.abraham@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/31.jpg",
        },
        {
          slot: "M13",
          name: "Wade May",
          gender: "male",
          age: 65,
          email: "wade.may@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/0.jpg",
        },
        {
          slot: "M14",
          name: "Julia Mitchell",
          gender: "female",
          age: 66,
          email: "julia.mitchell@example.com",
          picture: "https://randomuser.me/api/portraits/med/women/4.jpg",
        },
        {
          slot: "M15",
          name: "Adrian Hughes",
          gender: "male",
          age: 56,
          email: "adrian.hughes@example.com",
          picture: "https://randomuser.me/api/portraits/med/men/25.jpg",
        },
      ].map((person) => ({
        ...person,
        deathDate: randomDate(),
      })),
    },
  ].map((block, index) => ({
    ...block,
    image: `https://picsum.photos/1920/1080?random=${index}`,
  })),
};

function randomDate() {
  const start = new Date(1970, 0, 1);
  const end = new Date(2020, 11, 31);
  return new Date(
    start.getTime() + Math.random() * (end.getTime() - start.getTime())
  );
}

/* const baseBlocks = [
  {
    "id": "a",
    "description": "Under ancient cypress trees, the air carries a faint scent of resin and earth. Time seems slower here, as sunlight filters through the dense canopy.",
    "maxSlots": 20
  },
  {
    "id": "b",
    "description": "A serene area near the marble walkway, where footsteps echo softly between columns. The stone surface remains cool even under the afternoon sun.",
    "maxSlots": 20
  },
  {
    "id": "c",
    "description": "Nestled by the chapel ruins, moss covers fragments of old stone. The silence is broken only by distant bells carried on the wind.",
    "maxSlots": 20
  },
  {
    "id": "d",
    "description": "Beside the northern slope, tall grasses sway gently in the breeze. The scent of pine lingers, reminding travelers of the highlands beyond.",
    "maxSlots": 20
  },
  {
    "id": "e",
    "description": "A sunlit corner surrounded by ivy walls, where the warmth feels almost sacred. Small wildflowers bloom through cracks in the ancient stone.",
    "maxSlots": 20
  },
  {
    "id": "f",
    "description": "Overlooking a small pond, the water’s surface mirrors drifting clouds. The gentle hum of insects fills the still air around it.",
    "maxSlots": 20
  },
  {
    "id": "g",
    "description": "This secluded area rests under oak shadows, where light and dark intertwine. Fallen leaves create a soft path that muffles every step.",
    "maxSlots": 20
  },
  {
    "id": "h",
    "description": "Gravel paths wind through this section, bordered by low stone markers. Each corner reveals a hidden alcove cloaked in quiet stillness.",
    "maxSlots": 20
  },
  {
    "id": "i",
    "description": "Beyond the central archway, the space opens to a tranquil courtyard. The air feels heavier here, as if history itself lingers unseen.",
    "maxSlots": 20
  },
  {
    "id": "j",
    "description": "Quietly tucked near the south gate, the area is rarely disturbed. Morning mist often settles here, softening the outlines of the stones.",
    "maxSlots": 20
  },
  {
    "id": "k",
    "description": "This block lies on elevated ground, granting a view of the valley below. Breezes pass through often, carrying whispers of the forest edge.",
    "maxSlots": 20
  },
  {
    "id": "l",
    "description": "Near the fountain courtyard, the sound of water echoes between carved pillars. Pigeons gather here, unafraid of the gentle visitors passing by.",
    "maxSlots": 20
  },
  {
    "id": "m",
    "description": "Along the western edge, golden light lingers longer before dusk. The stones here are warm to the touch, keeping the day’s memory.",
    "maxSlots": 20
  }
]
;

async function generateData() {
  const output = { blocks: [] };

  for (const block of baseBlocks) {
    const res = await fetch(`https://randomuser.me/api/?results=${block.maxSlots}&nat=us,gb,ca`);
    const data = await res.json();

    const slots = data.results.map((user, i) => ({
      slot: `${block.id.toUpperCase()}${i + 1}`,
      name: `${user.name.first} ${user.name.last}`,
      gender: user.gender,
      age: user.dob.age,
      email: user.email,
      picture: user.picture.medium,
    }));

    output.blocks.push({
      id: block.id,
      description: block.description,
      maxSlots: block.maxSlots,
      slots,
    });
  }

  console.log(JSON.stringify(output, null, 2));
}

generateData();*/
