import { db } from "@/firebaseConfig";
import { addDoc, collection, getDocs } from "firebase/firestore";
import React, { useState } from "react";
import { Pressable, Text, View } from "react-native";

export default function Test() {
  const [hover, setHover] = useState(false);
  return (
    <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
      <Pressable
        onHoverIn={() => setHover(true)}
        onHoverOut={() => setHover(false)}
        style={{
          backgroundColor: hover ? "grey" : "black",
          padding: 20,
          borderRadius: 10,
        }}
        onPress={async () => {
          await uploadPlotOwners().catch(console.error);
        }}
      >
        <Text style={{ color: hover ? "black" : "white" }}>Hello World</Text>
      </Pressable>
    </View>
  );
}

async function fetchPlots() {
  const snapshot = await getDocs(collection(db, "deceaseds"));
  const plots = snapshot.docs.map((doc) => doc.data().plot);
  console.log(plots);
}

const plots = [
  "ph1_blk4_plot_16",
  "ph2_blk15_plot_3",
  "ph2_blk6_plot_13",
  "ph2_blk15_plot_10",
  "ph2_blk7_plot_6",
  "nph_blk11_plot_9",
  "ph2_blk3_plot_6",
  "nph_blk2_plot_6",
  "ph1_blk1_plot_15",
  "ph1_blk7_plot_4",
  "ph1_blk2_plot_11",
  "nph_blk6_plot_11",
  "nph_blk13_plot_9",
  "ph1_blk4_plot_3",
  "ph1_blk7_plot_9",
  "ph1_blk10_plot_3",
  "ph1_blk8_plot_8",
  "ph1_blk13_plot_5",
  "nph_blk14_plot_15",
  "ph1_blk11_plot_4",
  "ph1_blk3_plot_16",
  "ph1_blk3_plot_16",
  "nph_blk14_plot_4",
  "nph_blk9_plot_12",
  "ph2_blk11_plot_15",
  "ph1_blk13_plot_1",
  "ph1_blk9_plot_1",
  "nph_blk2_plot_1",
  "ph2_blk6_plot_2",
  "ph1_blk13_plot_6",
];

const firstNames = [
  "Juan",
  "Maria",
  "Jose",
  "Ana",
  "Luis",
  "Carmen",
  "Pedro",
  "Lucia",
];
const lastNames = [
  "Santos",
  "Reyes",
  "Cruz",
  "Bautista",
  "Gomez",
  "Torres",
  "Ramos",
  "Flores",
];

function randomFrom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function randomDate() {
  const date = new Date(Date.now() - Math.random() * 3.15e10); // random past year
  return date.toISOString().split("T")[0]; // "YYYY-MM-DD"
}

const owners = plots.map((plot) => ({
  plot,
  first_name: randomFrom(firstNames),
  middle_name: String.fromCharCode(65 + Math.floor(Math.random() * 26)) + ".",
  last_name: randomFrom(lastNames),
  address: `${Math.floor(Math.random() * 200) + 1} Sample St.`,
  phone: `+639${Math.floor(100000000 + Math.random() * 899999999)}`,
  email: `${Math.random().toString(36).substring(2, 7)}@mail.com`,
  purchase_date: randomDate(),
  deed_number: `DN-${Math.floor(10000 + Math.random() * 90000)}`,
  notes: "No additional notes.",
}));

export async function uploadPlotOwners() {
  const colRef = collection(db, "plot_owners");

  try {
    for (const owner of plotOwners) {
      await addDoc(colRef, owner);
    }
    console.log("✅ All plot owners uploaded successfully!");
  } catch (err) {
    console.error("❌ Error uploading plot owners:", err);
  }
}

const plotOwners = [
  {
    plot: "ph1_blk4_plot_16",
    first_name: "Jose",
    middle_name: "N.",
    last_name: "Reyes",
    address: "102 Sample St.",
    phone: "+639202242129",
    email: "azmkv@mail.com",
    purchase_date: "2025-01-08",
    deed_number: "DN-74126",
    notes: "No additional notes.",
  },
  {
    plot: "ph2_blk15_plot_3",
    first_name: "Luis",
    middle_name: "M.",
    last_name: "Santos",
    address: "66 Sample St.",
    phone: "+639429306185",
    email: "i0q2d@mail.com",
    purchase_date: "2025-10-20",
    deed_number: "DN-35178",
    notes: "No additional notes.",
  },
  {
    plot: "ph2_blk6_plot_13",
    first_name: "Pedro",
    middle_name: "J.",
    last_name: "Santos",
    address: "163 Sample St.",
    phone: "+639929689450",
    email: "tul0x@mail.com",
    purchase_date: "2025-05-17",
    deed_number: "DN-29360",
    notes: "No additional notes.",
  },
  {
    plot: "ph2_blk15_plot_10",
    first_name: "Lucia",
    middle_name: "N.",
    last_name: "Gomez",
    address: "179 Sample St.",
    phone: "+639454310048",
    email: "z1miu@mail.com",
    purchase_date: "2025-07-10",
    deed_number: "DN-50168",
    notes: "No additional notes.",
  },
  {
    plot: "ph2_blk7_plot_6",
    first_name: "Maria",
    middle_name: "Q.",
    last_name: "Bautista",
    address: "183 Sample St.",
    phone: "+639383708271",
    email: "36k8z@mail.com",
    purchase_date: "2025-07-25",
    deed_number: "DN-53943",
    notes: "No additional notes.",
  },
  {
    plot: "nph_blk11_plot_9",
    first_name: "Lucia",
    middle_name: "R.",
    last_name: "Santos",
    address: "116 Sample St.",
    phone: "+639586972432",
    email: "biiac@mail.com",
    purchase_date: "2025-04-06",
    deed_number: "DN-93475",
    notes: "No additional notes.",
  },
  {
    plot: "ph2_blk3_plot_6",
    first_name: "Lucia",
    middle_name: "A.",
    last_name: "Gomez",
    address: "69 Sample St.",
    phone: "+639190243335",
    email: "spywh@mail.com",
    purchase_date: "2024-12-19",
    deed_number: "DN-47313",
    notes: "No additional notes.",
  },
  {
    plot: "nph_blk2_plot_6",
    first_name: "Lucia",
    middle_name: "O.",
    last_name: "Cruz",
    address: "137 Sample St.",
    phone: "+639617831608",
    email: "gy9ee@mail.com",
    purchase_date: "2025-01-07",
    deed_number: "DN-91240",
    notes: "No additional notes.",
  },
  {
    plot: "ph1_blk1_plot_15",
    first_name: "Ana",
    middle_name: "V.",
    last_name: "Santos",
    address: "88 Sample St.",
    phone: "+639577453790",
    email: "iwacv@mail.com",
    purchase_date: "2025-10-18",
    deed_number: "DN-68304",
    notes: "No additional notes.",
  },
  {
    plot: "ph1_blk7_plot_4",
    first_name: "Ana",
    middle_name: "N.",
    last_name: "Cruz",
    address: "57 Sample St.",
    phone: "+639150856089",
    email: "9xl0a@mail.com",
    purchase_date: "2025-03-28",
    deed_number: "DN-83801",
    notes: "No additional notes.",
  },
  {
    plot: "ph1_blk2_plot_11",
    first_name: "Luis",
    middle_name: "U.",
    last_name: "Bautista",
    address: "191 Sample St.",
    phone: "+639928106121",
    email: "sbeyo@mail.com",
    purchase_date: "2025-06-05",
    deed_number: "DN-41268",
    notes: "No additional notes.",
  },
  {
    plot: "nph_blk6_plot_11",
    first_name: "Lucia",
    middle_name: "P.",
    last_name: "Bautista",
    address: "131 Sample St.",
    phone: "+639262846665",
    email: "z5zvu@mail.com",
    purchase_date: "2025-09-01",
    deed_number: "DN-87979",
    notes: "No additional notes.",
  },
  {
    plot: "nph_blk13_plot_9",
    first_name: "Jose",
    middle_name: "R.",
    last_name: "Torres",
    address: "107 Sample St.",
    phone: "+639916457641",
    email: "i9egb@mail.com",
    purchase_date: "2025-09-17",
    deed_number: "DN-75091",
    notes: "No additional notes.",
  },
  {
    plot: "ph1_blk4_plot_3",
    first_name: "Jose",
    middle_name: "O.",
    last_name: "Reyes",
    address: "194 Sample St.",
    phone: "+639247692083",
    email: "osnm3@mail.com",
    purchase_date: "2025-01-09",
    deed_number: "DN-55239",
    notes: "No additional notes.",
  },
  {
    plot: "ph1_blk7_plot_9",
    first_name: "Juan",
    middle_name: "I.",
    last_name: "Flores",
    address: "148 Sample St.",
    phone: "+639460369387",
    email: "6smly@mail.com",
    purchase_date: "2025-07-20",
    deed_number: "DN-51013",
    notes: "No additional notes.",
  },
  {
    plot: "ph1_blk10_plot_3",
    first_name: "Carmen",
    middle_name: "P.",
    last_name: "Bautista",
    address: "33 Sample St.",
    phone: "+639316737337",
    email: "1cnoe@mail.com",
    purchase_date: "2025-01-01",
    deed_number: "DN-58698",
    notes: "No additional notes.",
  },
  {
    plot: "ph1_blk8_plot_8",
    first_name: "Pedro",
    middle_name: "E.",
    last_name: "Bautista",
    address: "102 Sample St.",
    phone: "+639957537627",
    email: "450ow@mail.com",
    purchase_date: "2025-02-07",
    deed_number: "DN-39579",
    notes: "No additional notes.",
  },
  {
    plot: "ph1_blk13_plot_5",
    first_name: "Carmen",
    middle_name: "O.",
    last_name: "Gomez",
    address: "101 Sample St.",
    phone: "+639934475124",
    email: "93tlf@mail.com",
    purchase_date: "2025-07-09",
    deed_number: "DN-58433",
    notes: "No additional notes.",
  },
  {
    plot: "nph_blk14_plot_15",
    first_name: "Ana",
    middle_name: "C.",
    last_name: "Cruz",
    address: "191 Sample St.",
    phone: "+639860375614",
    email: "t0ewm@mail.com",
    purchase_date: "2025-06-10",
    deed_number: "DN-10414",
    notes: "No additional notes.",
  },
  {
    plot: "ph1_blk11_plot_4",
    first_name: "Lucia",
    middle_name: "V.",
    last_name: "Ramos",
    address: "58 Sample St.",
    phone: "+639321100247",
    email: "3t5v6@mail.com",
    purchase_date: "2024-12-26",
    deed_number: "DN-95513",
    notes: "No additional notes.",
  },
  {
    plot: "ph1_blk3_plot_16",
    first_name: "Jose",
    middle_name: "P.",
    last_name: "Santos",
    address: "24 Sample St.",
    phone: "+639998108388",
    email: "1jo8k@mail.com",
    purchase_date: "2025-04-24",
    deed_number: "DN-18422",
    notes: "No additional notes.",
  },
  {
    plot: "ph1_blk3_plot_16",
    first_name: "Maria",
    middle_name: "P.",
    last_name: "Torres",
    address: "37 Sample St.",
    phone: "+639436139133",
    email: "tygdx@mail.com",
    purchase_date: "2025-08-16",
    deed_number: "DN-79157",
    notes: "No additional notes.",
  },
  {
    plot: "nph_blk14_plot_4",
    first_name: "Carmen",
    middle_name: "O.",
    last_name: "Flores",
    address: "187 Sample St.",
    phone: "+639931423626",
    email: "3hwiu@mail.com",
    purchase_date: "2024-12-10",
    deed_number: "DN-14403",
    notes: "No additional notes.",
  },
  {
    plot: "nph_blk9_plot_12",
    first_name: "Juan",
    middle_name: "C.",
    last_name: "Flores",
    address: "44 Sample St.",
    phone: "+639570671598",
    email: "sfz9x@mail.com",
    purchase_date: "2024-12-21",
    deed_number: "DN-62138",
    notes: "No additional notes.",
  },
  {
    plot: "ph2_blk11_plot_15",
    first_name: "Jose",
    middle_name: "T.",
    last_name: "Flores",
    address: "81 Sample St.",
    phone: "+639242425259",
    email: "63p0e@mail.com",
    purchase_date: "2024-11-24",
    deed_number: "DN-62438",
    notes: "No additional notes.",
  },
  {
    plot: "ph1_blk13_plot_1",
    first_name: "Carmen",
    middle_name: "J.",
    last_name: "Flores",
    address: "98 Sample St.",
    phone: "+639307048908",
    email: "w5y6q@mail.com",
    purchase_date: "2024-12-01",
    deed_number: "DN-46338",
    notes: "No additional notes.",
  },
  {
    plot: "ph1_blk9_plot_1",
    first_name: "Juan",
    middle_name: "T.",
    last_name: "Reyes",
    address: "121 Sample St.",
    phone: "+639614753584",
    email: "x222p@mail.com",
    purchase_date: "2025-09-30",
    deed_number: "DN-38008",
    notes: "No additional notes.",
  },
  {
    plot: "nph_blk2_plot_1",
    first_name: "Pedro",
    middle_name: "P.",
    last_name: "Flores",
    address: "95 Sample St.",
    phone: "+639994480806",
    email: "unjh5@mail.com",
    purchase_date: "2025-04-26",
    deed_number: "DN-18122",
    notes: "No additional notes.",
  },
  {
    plot: "ph2_blk6_plot_2",
    first_name: "Lucia",
    middle_name: "M.",
    last_name: "Cruz",
    address: "155 Sample St.",
    phone: "+639447310007",
    email: "tra10@mail.com",
    purchase_date: "2025-04-08",
    deed_number: "DN-58751",
    notes: "No additional notes.",
  },
  {
    plot: "ph1_blk13_plot_6",
    first_name: "Pedro",
    middle_name: "E.",
    last_name: "Santos",
    address: "128 Sample St.",
    phone: "+639701850807",
    email: "y2dgt@mail.com",
    purchase_date: "2025-06-27",
    deed_number: "DN-65535",
    notes: "No additional notes.",
  },
];
