// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { Instance, Instances, useGLTF } from "@react-three/drei";
import React from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["3dmap_extrude1_b_ground"]: THREE.Mesh;
    ["3dmap_extrude1_b_road"]: THREE.Mesh;
    ["3dmap_extrude1_b_wall"]: THREE.Mesh;
    ["3d_map_blocks011"]: THREE.Mesh;
    ["3dmap_extrude1_b_edgeplots"]: THREE.Mesh;
    ["3dmap_extrude1_b_graves"]: THREE.Mesh;
    Circle003: THREE.Mesh;
    Circle003_1: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
    ["Tree.Leaf"]: THREE.MeshStandardMaterial;
    ["Tree.Trunk"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    require("@/assets/models/parkrealsize.glb")
  ) as GLTFResult;

  // Array of all tree positions and scales
  const trees = [
    { position: [-42.731, 5.96, 96.027], scale: 3.994 },
    { position: [-53.348, 5.96, 81.112], scale: 3.994 },
    { position: [-47.991, 8.387, 85.36], scale: 6.257 },
    { position: [-95.819, 5.96, 2.237], scale: 3.994 },
    { position: [-88.488, 8.174, -5.094], scale: 5.73 },
    { position: [-32.113, 5.96, 25.495], scale: 3.994 },
    { position: [-24.529, 7.424, 22.209], scale: 5.824 },
    { position: [-16.945, 5.96, 18.67], scale: 3.994 },
    { position: [0.246, 5.96, 10.833], scale: 3.994 },
    { position: [7.83, 5.96, 20.186], scale: 3.994 },
    { position: [1.004, 8.817, 64.68], scale: 10.32 },
    { position: [13.897, 10.877, 58.865], scale: 9.594 },
    { position: [3.28, 10.59, 77.067], scale: 11.157 },
    { position: [22.493, 10.03, 66.955], scale: 10.641 },
    { position: [42.211, 5.96, 46.731], scale: 3.994 },
    { position: [49.037, 7.872, 21.198], scale: 7.319 },
    { position: [41.453, 7.229, 13.866], scale: 5.488 },
    { position: [36.903, 5.96, 4.26], scale: 3.994 },
    { position: [26.285, 5.96, -0.796], scale: 3.994 },
    { position: [8.589, 5.96, -4.841], scale: 3.994 },
    { position: [-8.855, 7.79, -14.701], scale: 5.453 },
    { position: [-15.175, 5.96, -25.066], scale: 3.994 },
    { position: [13.139, 8.556, -45.795], scale: 5.991 },
    { position: [47.015, 7.909, -30.627], scale: 5.425 },
    { position: [52.071, 5.96, -22.285], scale: 3.994 },
    { position: [50.048, 5.96, -14.953], scale: 3.994 },
    { position: [55.863, 5.96, -11.92], scale: 3.994 },
    { position: [58.897, 5.96, 0.72], scale: 3.994 },
    { position: [67.239, 7.637, 4.007], scale: 5.756 },
    { position: [78.868, 5.96, -7.116], scale: 3.994 },
    { position: [89.233, 7.302, -3.577], scale: 5.331 },
    { position: [74.823, 7.608, -29.869], scale: 5.543 },
    { position: [105.665, 5.96, 7.293], scale: 3.994 },
    { position: [99.598, 7.27, -2.819], scale: 5.693 },
    { position: [97.828, 5.96, 23.726], scale: 3.994 },
    { position: [85.441, 5.96, 9.316], scale: 3.994 },
    { position: [91.255, 5.96, -42.509], scale: 3.994 },
  ];

  if (!nodes.Circle003?.geometry || !nodes.Circle003_1?.geometry) return null;

  return (
    <group {...props} dispose={null}>
      {/* Static meshes */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["3dmap_extrude1_b_ground"].geometry}
        material={materials.Material}
        position={[0, 0.1, 0]}
        scale={10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["3dmap_extrude1_b_road"].geometry}
        material={materials["Material.003"]}
        position={[-2.926, 0, 1.222]}
        scale={10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["3dmap_extrude1_b_wall"].geometry}
        material={materials["Material.001"]}
        position={[20.696, 0.73, 3.228]}
        scale={10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["3d_map_blocks011"].geometry}
        material={materials["Material.002"]}
        position={[-54.1, 3.564, 42.572]}
        scale={10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["3dmap_extrude1_b_edgeplots"].geometry}
        material={materials["Material.005"]}
        position={[37.49, 2.493, -3.581]}
        scale={10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["3dmap_extrude1_b_graves"].geometry}
        material={materials["Material.004"]}
        position={[28.823, 0.201, 3.868]}
        scale={10}
      />

      {/* Instanced trees */}
      <Instances>
        {/* Leaf geometry */}
        <instancedMesh
          args={[
            nodes.Circle003.geometry,
            materials["Tree.Leaf"],
            trees.length,
          ]}
          castShadow
          receiveShadow
        >
          {trees.map((tree, i) => (
            <Instance
              key={i}
              position={tree.position as [number, number, number]}
              scale={tree.scale}
            />
          ))}
        </instancedMesh>

        {/* Trunk geometry */}
        <instancedMesh
          args={[
            nodes.Circle003_1.geometry,
            materials["Tree.Trunk"],
            trees.length,
          ]}
          castShadow
          receiveShadow
        >
          {trees.map((tree, i) => (
            <Instance
              key={i}
              position={tree.position as [number, number, number]}
              scale={tree.scale}
            />
          ))}
        </instancedMesh>
      </Instances>
    </group>
  );
}

useGLTF.preload(require("@/assets/models/parkrealsize.glb"));
