const sampleData = {
  block: [
    {
      id: "a",
      status: "green",
      description: "lorem1 ipsum dolor sit amet",
      slot: [
        {
          id: 0,
          name: "John L. Doe",
          lifespan: { from: 1956, to: 2012 },
          sex: "male",
        },
        {
          id: 1,
          name: "Alice M. Smith",
          lifespan: { from: 1942, to: 2001 },
          sex: "female",
        },
        {
          id: 2,
          name: "Robert Johnson",
          lifespan: { from: 1961, to: 2020 },
          sex: "male",
        },
        {
          id: 3,
          name: "Emily G. Williams",
          lifespan: { from: 1978, to: 2033 },
          sex: "female",
        },
        {
          id: 4,
          name: "Michael Brown",
          lifespan: { from: 1933, to: 1999 },
          sex: "male",
        },
        {
          id: 5,
          name: "Sophia A. Jones",
          lifespan: { from: 1980, to: 2040 },
          sex: "female",
        },
        {
          id: 6,
          name: "David A. Garcia",
          lifespan: { from: 1950, to: 2010 },
          sex: "male",
        },
        {
          id: 7,
          name: "Olivia R. Miller",
          lifespan: { from: 1990, to: 2065 },
          sex: "female",
        },
        {
          id: 8,
          name: "William H. Davis",
          lifespan: { from: 1925, to: 1985 },
          sex: "male",
        },
        {
          id: 9,
          name: "Isabella C. Rodriguez",
          lifespan: { from: 1965, to: 2022 },
          sex: "female",
        },
        {
          id: 10,
          name: "James Martinez",
          lifespan: { from: 1955, to: 2011 },
          sex: "male",
        },
        {
          id: 11,
          name: "Mia Hernandez",
          lifespan: { from: 1988, to: 2071 },
          sex: "female",
        },
        {
          id: 12,
          name: "Charles M. Lopez",
          lifespan: { from: 1919, to: 1980 },
          sex: "male",
        },
        {
          id: 13,
          name: "Amelia Gonzalez",
          lifespan: { from: 1995, to: 2075 },
          sex: "female",
        },
        {
          id: 14,
          name: "Thomas R. Wilson",
          lifespan: { from: 1947, to: 2003 },
          sex: "male",
        },
        {
          id: 15,
          name: "Charlotte Anderson",
          lifespan: { from: 1971, to: 2035 },
          sex: "female",
        },
        {
          id: 16,
          name: "Daniel S. Thomas",
          lifespan: { from: 1960, to: 2021 },
          sex: "male",
        },
        {
          id: 17,
          name: "Abigail J. Taylor",
          lifespan: { from: 2000, to: 2085 },
          sex: "female",
        },
        {
          id: 18,
          name: "Matthew Moore",
          lifespan: { from: 1938, to: 1994 },
          sex: "male",
        },
        {
          id: 19,
          name: "Ella R. Jackson",
          lifespan: { from: 1993, to: 2063 },
          sex: "female",
        },
      ].map((person) => ({
        ...person,
        image: `https://avatar.iran.liara.run/public/${person.sex}`,
      })),
    },
    {
      id: "b",
      status: "yellow",
      description: "lorem2 ipsum dolor sit amet",
      slot: [
        {
          id: 0,
          name: "Liam J. Walker",
          lifespan: { from: 1950, to: 2008 },
          sex: "male",
        },
        {
          id: 1,
          name: "Chloe Bennett",
          lifespan: { from: 1972, to: 2030 },
          sex: "female",
        },
        {
          id: 2,
          name: "Noah Reed",
          lifespan: { from: 1945, to: 2005 },
          sex: "male",
        },
        {
          id: 3,
          name: "Grace L. Perry",
          lifespan: { from: 1963, to: 2020 },
          sex: "female",
        },
        {
          id: 4,
          name: "Benjamin C. Brooks",
          lifespan: { from: 1928, to: 1992 },
          sex: "male",
        },
        {
          id: 5,
          name: "Lily S. Rivera",
          lifespan: { from: 1984, to: 2060 },
          sex: "female",
        },
        {
          id: 6,
          name: "Ethan Wood",
          lifespan: { from: 1975, to: 2035 },
          sex: "male",
        },
        {
          id: 7,
          name: "Zoe M. Coleman",
          lifespan: { from: 1990, to: 2070 },
          sex: "female",
        },
        {
          id: 8,
          name: "Lucas R. Sanders",
          lifespan: { from: 1939, to: 2000 },
          sex: "male",
        },
        {
          id: 9,
          name: "Aria Foster",
          lifespan: { from: 1969, to: 2029 },
          sex: "female",
        },
        {
          id: 10,
          name: "Henry P. Morgan",
          lifespan: { from: 1958, to: 2015 },
          sex: "male",
        },
        {
          id: 11,
          name: "Scarlett Hayes",
          lifespan: { from: 1986, to: 2050 },
          sex: "female",
        },
        {
          id: 12,
          name: "Owen V. Bryant",
          lifespan: { from: 1943, to: 2003 },
          sex: "male",
        },
        {
          id: 13,
          name: "Sofia N. Kim",
          lifespan: { from: 1997, to: 2081 },
          sex: "female",
        },
        {
          id: 14,
          name: "Jack T. Chavez",
          lifespan: { from: 1930, to: 1990 },
          sex: "male",
        },
        {
          id: 15,
          name: "Avery Harper",
          lifespan: { from: 1979, to: 2042 },
          sex: "female",
        },
        {
          id: 16,
          name: "Logan D. Wells",
          lifespan: { from: 1966, to: 2025 },
          sex: "male",
        },
        {
          id: 17,
          name: "Nora K. Black",
          lifespan: { from: 2001, to: 2078 },
          sex: "female",
        },
        {
          id: 18,
          name: "Elijah Greene",
          lifespan: { from: 1952, to: 2010 },
          sex: "male",
        },
        {
          id: 19,
          name: "Hazel Y. Stone",
          lifespan: { from: 1992, to: 2062 },
          sex: "female",
        },
      ].map((person) => ({
        ...person,
        image: `https://avatar.iran.liara.run/public/${person.sex}`,
      })),
    },
    {
      id: "c",
      status: "red",
      description: "lorem3 ipsum dolor sit amet",
      slot: [
        {
          id: 0,
          name: "Samuel B. Hayes",
          lifespan: { from: 1948, to: 2006 },
          sex: "male",
        },
        {
          id: 1,
          name: "Madison Clark",
          lifespan: { from: 1975, to: 2032 },
          sex: "female",
        },
        {
          id: 2,
          name: "Jacob D. Ellis",
          lifespan: { from: 1933, to: 1998 },
          sex: "male",
        },
        {
          id: 3,
          name: "Ella Morgan",
          lifespan: { from: 1980, to: 2043 },
          sex: "female",
        },
        {
          id: 4,
          name: "Ryan F. Hughes",
          lifespan: { from: 1959, to: 2014 },
          sex: "male",
        },
        {
          id: 5,
          name: "Victoria R. Bailey",
          lifespan: { from: 1990, to: 2072 },
          sex: "female",
        },
        {
          id: 6,
          name: "Nathaniel Gray",
          lifespan: { from: 1922, to: 1981 },
          sex: "male",
        },
        {
          id: 7,
          name: "Zoe M. Powell",
          lifespan: { from: 1967, to: 2027 },
          sex: "female",
        },
        {
          id: 8,
          name: "Aaron B. Cooper",
          lifespan: { from: 1945, to: 2005 },
          sex: "male",
        },
        {
          id: 9,
          name: "Lillian Adams",
          lifespan: { from: 1978, to: 2038 },
          sex: "female",
        },
        {
          id: 10,
          name: "Evan T. Bennett",
          lifespan: { from: 1936, to: 1994 },
          sex: "male",
        },
        {
          id: 11,
          name: "Grace Mitchell",
          lifespan: { from: 1995, to: 2073 },
          sex: "female",
        },
        {
          id: 12,
          name: "Coleman J. Foster",
          lifespan: { from: 1952, to: 2010 },
          sex: "male",
        },
        {
          id: 13,
          name: "Natalie Quinn",
          lifespan: { from: 1983, to: 2046 },
          sex: "female",
        },
        {
          id: 14,
          name: "Jason R. Ross",
          lifespan: { from: 1960, to: 2018 },
          sex: "male",
        },
        {
          id: 15,
          name: "Audrey Bennett",
          lifespan: { from: 1970, to: 2035 },
          sex: "female",
        },
        {
          id: 16,
          name: "Dominic H. Powell",
          lifespan: { from: 1947, to: 2004 },
          sex: "male",
        },
        {
          id: 17,
          name: "Claire J. Ward",
          lifespan: { from: 1999, to: 2079 },
          sex: "female",
        },
        {
          id: 18,
          name: "Gavin K. Long",
          lifespan: { from: 1931, to: 1988 },
          sex: "male",
        },
        {
          id: 19,
          name: "Violet S. James",
          lifespan: { from: 1991, to: 2061 },
          sex: "female",
        },
      ].map((person) => ({
        ...person,
        image: `https://avatar.iran.liara.run/public/${person.sex}`,
      })),
    },
  ].map((block) => ({
    ...block,
    image: "https://picsum.photos/id/400/400?grayscale&blur=2",
  })),
};
export default sampleData;
